OOP school library: add basic UI
mpa-mxiang/school_library pull request #4
Opened 2023-08-02 00:42 UTC by mpa-mxiang

For this PR, I:

- Build interactive console apps.
- Run a program using the command line.

2023-08-02 01:11 UTC, Olamarx requested changes
Hi @mpa-mxiang,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights
- Linters passed ✔️
- Readme professional ✔️
- Readable codebase ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 01:11 UTC, Olamarx commented on app.rb
> +      create_student
- [ ] Both create teacher and create student are under create person and not separated, the fact that you separated it makes no space for list rentals but only create rentals. I will implore you to add it.

### Expected UI
![image](https://github.com/mpa-mxiang/school_library/assets/86200356/a6ebc50b-b225-43d6-8677-47e6500ed989)

### Your UI
![image](https://github.com/mpa-mxiang/school_library/assets/86200356/0d370a10-be44-4462-ae98-b9d106376759)

2023-08-04 21:53 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @mpa-mxiang, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Good console UI design :white_check_mark: 
- [x] Application works as expected :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark:   
- [x] Implemented all the required changes from the previous reviewer :white_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-04 22:49 UTC, mpa-mxiang commented
Thank you @Felix45 for the approval!

2023-08-04 22:51 UTC, merged